// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsotlcfjenfkwxnjhlcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indzb3RsY2ZqZW5ma3d4bmpobGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjc3MDYsImV4cCI6MjA1OTcwMzcwNn0.XlmcnAMx6Tq8_O_1bLFOT2b_ATajOZQlFPBkrLZT1WM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);